### ISSUE TITLE
can't make HTTPRequest

### ISSUE THREAD

**Issue by hasgardee** [checkout/checkoutkit-ios#14]
Swift 3.1
Xcode 8.3.1
Checkout 3.0.1

When trying to call HTTPRequest postRequest, completion handler making some issue 

> Using 'Serializable' as a concrete type conforming to protocol 'Serializable' is not supported

Is there have any example for using HTTPRequest?
Could anyone please guide me through the steps?

Is possible to do card charging and other api calls from inside the app with card token using Checkout HTTPRequest Class? if yes, is it okay to make calls without HTTPRequest Class? or we should have to make card charging related api calls from server ?

**Comment by nicolas-maalouf-cko** [comment]
Hi,

Can you please post the sample code you're using to get the Serializable error?

Our mobile kits are to be used exclusively to:
1) Run validation checks on card data 
2) Create a card token using your public key

All the other steps of the payment flow involving your secret key are to be done on your server:
>> Send the obtained card token from your mobile app to your server to do a charge.

**Comment by hasgardee** [comment]
```
import UIKit
import CheckoutKit

class ChargeController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
@IBAction func charge(_ sender: AnyObject) {

        HTTPRequest.postRequest("https://link", payload: "[]", pk: "pk___", debug: true, logger: log) { (resp: Response<Serializable>) in
            
        }
        
        
    }
}
```

okay.. so, for what kind of requests we make to checkout server using  HTTPRequest?

**Comment by nicolas-maalouf-cko** [comment]
You can have a look at the below code to use CheckoutKit.
No need to explicitly call HTTPRequest as it's already called within the kit.


```
func getCardToken() {
        
        var ck: CheckoutKit? = nil
        let customerDetails = CustomerDetails(address1: "test address 1",
                                              address2: "test address2",
                                              postCode: "B16123",
                                              country: "GB",
                                              city: "London",
                                              state: "xyz",
                                              phoneNumber: "7777777777",
                                              phoneCountryCode: "44")
        
        do {
            try ck = CheckoutKit.getInstance("pk_test_XXXXXXXXX",
                                             env: Environment.SANDBOX)
        } catch _ as NSError {
        
        }
        
        if ck != nil {
            if (CardValidator.validateCardNumber("4242424242424242")) {
                
                var card: Card? = nil
                do {
                    try card = Card(name: "test name",
                                    number: "4242424242424242",
                                    expYear: "2018",
                                    expMonth: "06",
                                    cvv: "100",
                                    billingDetails: customerDetails)
                    
                } catch _ as CardError {
                    
                } catch _ as NSError {
                    
                }
                if card != nil {
                    ck!.createCardToken(card!, completion:{ (resp: Response<CardTokenResponse>) -> Void in
                        if (resp.hasError) {
                           
                        } else {
                            print (resp.model?.cardToken)
                                                    }
                    })
                }
            }
        }
    }
```

**Comment by hasgardee** [comment]
okay got it. thanks :)

**Comment by TechTauseel** [comment]
Can you please tell me where i need pass amount payload

**Comment by nicolas-maalouf-cko** [comment]
Hi @TechTauseel the mobile sdk allows you to generate a temporary card token.
You then need to send this card token to your backend server from where you do a payment request with card token:
https://docs.checkout.com/docs/authorize-a-payment

You can specify the amount and other parameters there
