### ISSUE TITLE
Sample app is getting crashes.

### ISSUE THREAD

**Issue by ajumalebrahim** [checkout/checkoutkit-ios#15]
Just downloaded the sample app and try to run the app, loaded splash screen and it crashed.

**Comment by nicolas-maalouf-cko** [comment]
Hi, can you please give us a bit more details?

What branch are you using?
What version of Xcode are you on?

What app did you actually try to run?

Thanks

**Comment by ajumalebrahim** [comment]
Am using master banch in xcode 8.3.2 . I tried to run CheckoutKitExample project.

**Comment by nicolas-maalouf-cko** [comment]
Hi, I just tried running it on that same environment inside the simulator and it worked.

Can you please give us more details around anything logged in the console?

Thanks

**Comment by elvi117** [comment]
@nicolas-maalouf-cko  In newest Swift version issue is in ViewController at line 40: 
`Argument of '#selector' refers to instance method 'handleSingleTap' that is not exposed to Objective-C`

Solution: 
add @objc to function `handleSingleTap(_ recognizer: UITapGestureRecognizer)`
PR: https://github.com/checkout/checkoutkit-ios/pull/18

**Comment by nicolas-maalouf-cko** [comment]
Thanks for the fix @elvi117 ! 
Did it get rid of the crash?

**Comment by elvi117** [comment]
@nicolas-maalouf-cko  great! It works well :) many thanks

Additional I strongly recommended to add .podspec file to project locally https://github.com/checkout/checkoutkit-ios/pull/19 , what do you think about it ? While you dislike it feel free to remove that PR 😄
