### ISSUE TITLE
Unable to switch between Sandbox & Live due to condition if (ck == nil)

### ISSUE THREAD

**Issue by chatarveer** [checkout/checkoutkit-ios#16]
My Code. Here, I am checking if the user is pointing to LIVE or not. Here in my code, I am passing right KEY & Environment.

if hahObj.is_live_user == true {
      do {
        try ck = CheckoutKit.getInstance("Live-Key",
                                         env: Environment.LIVE)
      } catch _ as NSError {
        print(" Error Generated")
      }
    }else {
      do {
        try ck = CheckoutKit.getInstance("Test-Key",
                                         env: Environment.SANDBOX)
      } catch _ as NSError {
        print(" Error Generated ")
      }
    }

**The method of the library.**
    open class func getInstance(_ pk: String, env: Environment) throws -> CheckoutKit? {
        if (ck == nil) {
            ck = try CheckoutKit(pk: pk, env: env, debug: true, logger: Log.getLog())
        }
        return ck
    }

Here, **ck** is not re-init when I log out and log in my LIVE user, so this **ck** is present in memory (not nil), which is creating Sandbox CK, instead of LIVE again. 

Once I restart App, It releases all variables from memory & issue is resolved. 
In Development Mode, Switching is necessary & should be tackled properly.
Thanks.

**Comment by nicolas-maalouf-cko** [comment]
Hi @veer-suthar , are you planning to include both environments within the same app?

We recommend starting a new session when switching environments, which can be done by restarting the app.
