### ISSUE TITLE
Saving cards without PCI Certification 

### ISSUE THREAD

**Issue by hasgarPie** [checkout/checkoutkit-ios#17]
_Actually this is not an issue. its a doubt. i'm asking this here because its bit urgent. May be this will help your other customers too_

We don't have a PCI certification. but we should want to provide option for user to save cards in our app. I think using checkout.com which is possible without PCI. let me explain how we are planning to do. we will use ios sdk and get the card details from user using our own UI(if not possible please mention).then we will make a token using sdk and we will send that token that to the server and from server make request to merchant api(charge with token) and then we will charge the card. then we will save card_id (which we will get from response) , card's first 4 and last 4 digits, expiry month and year to the our server. then next time we will show that card(first and last 4 digits and expiry month and year, will ask for cvv) in our app for that user and if user choose to pay using that we will make the call to merchant api(charge with card id). 
Is there any problem with flow? Please guide me

**Comment by nicolas-maalouf-cko** [comment]
Hi Hasgar,

The flow you described is correct.

Just make sure to save the card IDs on your backend server and not within the mobile app.
You can then request charge with card IDs from your mobile app by sending an identifier linked to that user.

Flow example:
* Create card token with mobile SDK
* Send card token to your server and do a successful charge with card token from there, return the success result and display it in the mobile app
* Save the returned card ID on your server linking it to the current user, and notify the app that the current user has a new saved card with a unique identifier you generate on your end
* Your backend server can communicate the last4 digits back to the mobile app so you can display them to the user as an identifier for his card for future charges
* For future charges you would send requests from the mobile app to your backend server looking like "charge user X with card with identifier XYZ"
* The backend server will then look up the card ID of this card and does a charge with card ID

**Comment by hasgarPie** [comment]
Thanks @nicolas-maalouf-cko for the quick response 👍
