### ISSUE TITLE
Swift 4 compatibility

### ISSUE THREAD

**Issue by AdithyaReddy** [checkout/checkoutkit-ios#22]
In the Example folder 'ViewController.swift' file, "handleSingleTap" function needs to be marked as @objc. 

I see that it has been fixed in the Pod version 3.0.4 and above. Am currently on version 3.0.3. The problem is when I try to update to the latest version(3.0.5), it says "Pod version doesnt exist". 

May I know why is the pod version restricted to just 3.0.3?

**Comment by nicolas-maalouf-cko** [comment]
Hi @AdithyaReddy 
Can you please try again now?

**Comment by AdithyaReddy** [comment]
Perfect. Am able to update to the latest version(3.0.5) now. Thanks for the quick response.
