### ISSUE TITLE
fatal error: '<Project-Name>-Swift.h' file not found

### ISSUE THREAD

**Issue by siddharthsuneel** [checkout/checkoutkit-ios#25]
@nicolas-maalouf-cko  I have followed the steps mentioned in Readme.md file & project is able to build on xcode successfully, But When I tried build it from terminal using xcodebuild command it is throwing error that '<Project-Name>-Swift.h' file not found.
I am using  **CheckoutKit objective-c** in my project.

@nicolas-maalouf-cko  can you please explain the purpose of adding this '<Project-Name>-Swift.h' file in our project ?

**Comment by nicolas-maalouf-cko** [comment]
Hi @siddharthsuneel are you using the objective-c bridge?

**Comment by siddharthsuneel** [comment]
@nicolas-maalouf-cko  Yes, we are using objective c bridge.

**Comment by nicolas-maalouf-cko** [comment]
Unfortunately this is how bridging swift code to objective-c works;

Have you followed the different steps in the readme of the objective-c branch?

**Comment by siddharthsuneel** [comment]
@nicolas-maalouf-cko  Yes I have followed the steps, it is getting build successfully on xcode it is only showing error when I am trying to build it from terminal.

@nicolas-maalouf-cko  one more request, can we release a cocoapod for objective version of this library also ?

**Comment by AbhijitNaik48** [comment]
@nicolas-maalouf-cko  I have followed the steps mentioned in Readme.md file.And created bridging file.When I run the project ,its showing 'Projectname-Swift.h' file not found.Kindly give me solution for that.

**Comment by siddharthsuneel** [comment]
@ABHIJITNAIKIOS  are you using Objective c version of it ?

**Comment by AbhijitNaik48** [comment]
@siddharthsuneel  I got that point . Now its working fine.

**Comment by siddharthsuneel** [comment]
@ABHIJITNAIKIOS  can you share your solution that you have implemented here, so that it will help others who will face this same issue...

**Comment by AbhijitNaik48** [comment]
@siddharthsuneel  Can you specify your issues . So that I can help you

**Comment by siddharthsuneel** [comment]
@ABHIJITNAIKIOS  I have not used objective c version of it, I have used that swift Pod for integrating this payment gateway.

**Comment by zhfwch** [comment]
Maybe you don't need to followed the steps.
This is my ways.
In Objective-C Project, create a new '***.swift', then '-swift.h' and '-Briding-Header.h' had created.
Last, drag and drop it to your project in Xcode and choose the "Create groups" option. 
Clean your project and build again.
