### ISSUE TITLE
need to specify 'swift_version' in CheckoutKit.podspec

### ISSUE THREAD

**Issue by siddharthsuneel** [checkout/checkoutkit-ios#26]
@nicolas-maalouf-cko Getting the following when trying to build project containing CheckoutKit Pod.

> The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

I will be happy to submit a PR for this...

**Comment by nicolas-maalouf-cko** [comment]
Hi @siddharthsuneel 

Please feel free to submit a PR

**Comment by siddharthsuneel** [comment]
@nicolas-maalouf-cko  Kindly merge PR #27 . I have to use it in my project just now...

**Comment by siddharthsuneel** [comment]
@nicolas-maalouf-cko  Please release a new version of pod also. I am still facing that same issue...
