### ISSUE TITLE
Compatiblility issue with xcode 9.

### ISSUE THREAD

**Issue by siddharthsuneel** [checkout/checkoutkit-ios#28]
CheckoutKit pod is not compatible with Xcode 9.x also it is not working with swift 4.x

> pod 'DMIPaymentCheckout' version 3.0.5 is incompatible with Xcode 9 & above.

Below is the screenshot attached.

<img width="424" alt="screen shot 2018-07-19 at 4 19 32 pm" src="https://user-images.githubusercontent.com/15324076/42938467-fc14e1dc-8b6f-11e8-8909-74a9940492f2.png">

@nicolas-maalouf-cko  My team would more than happy to submit some PR for this purpose.

**Comment by nicolas-maalouf-cko** [comment]
@siddharthsuneel please go ahead if it's easy for you, but before I merge the code we need to make sure it remains compatible with older versions of Xcode
