### ISSUE TITLE
CardProviderResponse's mistake

### ISSUE THREAD

**Issue by zhfwch** [checkout/checkoutkit-ios#30]
In CheckoutKitObjC.m, the @selecotr(getCardProviders:failure:) and @selector(createCardToken:success:failure) maybe have a mistake. 
The failure's block return NSJSONSerialization's jsonError.

**Comment by nicolas-maalouf-cko** [comment]
@zhfwch closing this issue for now;
This was a limitation of the bridging done to Objective-C.
Please reopen it if it has caused any issues in your project
