### ISSUE TITLE
Show error after update xcode

### ISSUE THREAD

**Issue by zahedul** [checkout/checkoutkit-ios#6]
I am using swift 2, and development target is 8.1. thanks in advance. 

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
<img width="1280" alt="screen shot 2016-09-16 at 4 05 36 am" src="https://cloud.githubusercontent.com/assets/1929044/18569178/dc88054c-7bc2-11e6-9e0e-f18c3dc1a5e7.png">

**Comment by nicolas-maalouf-cko** [comment]
Hi @zahedul 

It seems you are using Xcode 8.
Can you please try to set the "Use Legacy Swift Language Version" in your build settings?

For reference: 
http://stackoverflow.com/questions/37835397/use-swift-2-2-in-xcode-8

**Comment by zahedul** [comment]
solved it already by adding in podfile
`
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end
`

thanks
