### ISSUE TITLE
Xcode 8 compatability

### ISSUE THREAD

**Issue by magnett** [checkout/checkoutkit-ios#7]
The sample project doesn't compile under Xcode 8 (compiler errors). I tried to convert to Swift 2.3 without any success and later on to Swift 3.0.
Could you provide an updated version for Xcode 8? A port to objective-c for improved compatibility would also be nice. You know that it will not compile again when Apple releases the next Swift version, right?  :)

**Comment by nicolas-maalouf-cko** [comment]
Hi @magnett 

We are working on adapting the sample project to the new Xcode release.

Meanwhile could you please try to have a look at the workaround found [here](https://github.com/checkout/checkoutkit-ios/issues/6).

Another solution could be the below doing the following changes in build settings:
- Embedded Content Contains Swift Code =Yes
- Runpath Search Paths @executable_path/Frameworks

**Comment by saad-ansari** [comment]
Hi @nicolas-maalouf-cko 

Even with Objective-C it is not working on Xcode 8. Let me know if there is any solution at the moment!!

**Comment by nicolas-maalouf-cko** [comment]
Hi @saad-ansari 

Can you please let me know how you integrated the library in Xcode 8?
The [current master branch](https://github.com/checkout/checkoutkit-ios) should work with Swift 3 on Xcode 8.

**Comment by saad-ansari** [comment]
Thanks for the response.
Well i'm following below link to integrate Checkout in my Objective C project.

https://github.com/checkout/checkoutkit-ios/tree/objective-c

which is working in Xcode 7.3.1 but not on Xcode 8

**Comment by magnett** [comment]
@nicolas-maalouf-cko that's because Xcode 8 supports only Swift 2.3 & 3.0 and that branch does not support any of them. I had to manually select and edit the swift files i needed from the repository.

**Comment by nicolas-maalouf-cko** [comment]
Thanks @magnett 
We're building an updated Objective-c bridge that supports Swift 3.0

**Comment by nicolas-maalouf-cko** [comment]
- objective-c branch has been updated and is now compatible with Swift 3 / Xcode 8.
- objective-c-swift2 branch has Swift 2 / Xcode 7 compatible code
